// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using moli.api.Models;

namespace moli.api.Migrations
{
    [DbContext(typeof(MoliContext))]
    partial class UserContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687");

            modelBuilder.Entity("moli.api.Models.Lesson", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<long?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Lessons");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Numbers"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Days"
                        });
                });

            modelBuilder.Entity("moli.api.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Email = "ranjithvenkatesh@hotmail.com",
                            Name = "Ranjith"
                        },
                        new
                        {
                            Id = 2L,
                            Email = "ranjith.venkatesh@mossandlichens.com",
                            Name = "Venkatesh"
                        });
                });

            modelBuilder.Entity("moli.api.Models.Lesson", b =>
                {
                    b.HasOne("moli.api.Models.User")
                        .WithMany("Lessons")
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
